// Configuration des objets interactifs du niveau monde
export const WORLD_INTERACTIVE_OBJECTS = [
  {
    id: "joshua",
    svgName: "joshua-goldberg",
    position: [0, 0, 0],
    size: 300,
    useVibration: true,
    vibrationIntensity: 5,
    vibrationSpeed: 2,
    persona: {
      id: "joshua-persona",
      name: "Joshua Goldberg",
      type: "persona",
    },
    text: "Joshua Goldberg - The creator of the variations",
    isInteractive: true,
    interactionType: "audio_fragment",
    audioFragment: "intro",
    boundingBox: {
      width: 200,
      height: 300,
      depth: 200,
    },
    contentData: {
      title: "Joshua Goldberg",
      text: "The enigmatic creator of the Goldberg Variations. A controversial figure who spent countless hours online, weaving complex narratives and identities across digital realms. His musical genius emerges from the chaos of internet culture.",
      type: "character",
    },
  },
  {
    id: "heart1",
    svgName: "heart-1",
    position: [600, -150, 100],
    size: 25,
    useVibration: true,
    vibrationIntensity: 2,
    vibrationSpeed: 3,
    text: "Love in the digital air",
    isInteractive: false,
    boundingBox: {
      width: 100,
      height: 100,
      depth: 100,
    },
    contentData: {
      title: "Floating Heart",
      text: "A symbol of love drifting through cyberspace, representing the genuine emotions that can emerge even from the most chaotic online interactions and digital personas.",
      type: "decoration",
    },
  },
  {
    id: "trollface",
    svgName: "trollface",
    position: [-250, 400, -100],
    size: 100,
    useVibration: true,
    vibrationIntensity: 2.5,
    vibrationSpeed: 2.5,
    text: "The ultimate troll face",
    isInteractive: false,
    boundingBox: {
      width: 100,
      height: 100,
      depth: 100,
    },
    contentData: {
      title: "Internet Troll",
      text: "The iconic face born from 4chan's chaotic depths. A symbol of the imageboard culture where anonymous users crafted memes that would define internet humor for generations.",
      type: "decoration",
    },
  },
  {
    id: "ak47",
    svgName: "ak47",
    position: [200, -350, 200],
    size: 100,
    useVibration: true,
    vibrationIntensity: 3,
    vibrationSpeed: 2,
    text: "Digital warfare weapon",
    isInteractive: true,
    interactionType: "retro_window",
    boundingBox: {
      width: 100,
      height: 100,
      depth: 100,
    },
    contentData: {
      title: "Cyber Weapon",
      text: "A symbol of online conflict and information warfare. Representing the darker side of digital interactions where words become weapons and identities become battlefields.",
      type: "weapon",
      retroWindow: {
        title: "DIGITAL WARFARE ACCESSED",
        texts: [
          "INITIATING CYBER PROTOCOL...\n\nSYSTEM STATUS: ONLINE\nACCESS LEVEL: ADMINISTRATOR\nSECURITY: BYPASSED",
          "HACKING THE MAINFRAME...\n\n> Connecting to remote server...\n> Exploiting buffer overflow...\n> Root access obtained",
          "BREACHING SECURITY FIREWALL...\n\nFIREWALL STATUS: COMPROMISED\nINTRUSION DETECTED: FALSE\nSTEALTH MODE: ACTIVE",
          "DOWNLOADING CLASSIFIED DATA...\n\n[████████████████████] 100%\n\nFiles retrieved:\n- government_secrets.zip\n- alien_contact.txt\n- illuminati_members.db",
          "UPLOADING VIRUS PAYLOAD...\n\n> Injecting malicious code...\n> Establishing backdoor...\n> Payload deployed successfully",
          "SYSTEM COMPROMISED. ACCESS GRANTED.\n\nWELCOME TO THE MATRIX\n\nYou are now part of the resistance.\nThe truth is out there.",
          "WELCOME TO THE DARK WEB...\n\n.onion sites loaded:\n- Anonymous Market\n- Whistleblower Portal\n- Digital Underground\n\nBrowse at your own risk.",
          "ANONYMOUS NETWORK ESTABLISHED.\n\nYour identity is now protected.\nIP: 127.0.0.1 (localhost)\nLocation: Cyberspace\nStatus: Ghost in the machine",
          "TROLLING SEQUENCE ACTIVATED...\n\n> Preparing memes...\n> Loading rickroll.mp4...\n> Target acquired: normies\n> Deploying chaos...",
          "MEME WARFARE DEPLOYED.\n\nPEPE ARMY: MOBILIZED\nRAGE COMICS: LOADED\nINTERNET CULTURE: WEAPONIZED\n\nThe meme war has begun.",
        ],
        image: null,
      },
    },
  },
  {
    id: "astroboy",
    svgName: "astroboy",
    position: [-300, -300, 200],
    size: 150,
    useVibration: true,
    vibrationIntensity: 4,
    vibrationSpeed: 1.5,
    persona: {
      id: "thug-persona",
      name: "You Suck My Life",
      type: "persona",
    },
    text: "You Suck My Life - The robotic alter ego",
    isInteractive: true,
    interactionType: "audio_fragment",
    audioFragment: "intro",
    boundingBox: {
      width: 100,
      height: 150,
      depth: 200,
    },
    contentData: {
      title: "You Suck My Life",
      text: "The beloved robot from geek culture, Astro Boy represents the fusion of humanity and technology. A symbol of how digital natives like Joshua found identity through anime, manga, and the endless worlds of Japanese pop culture.",
      type: "character",
    },
  },
];

// Configuration des objets non interactifs (étoiles fixes)
export const WORLD_NON_INTERACTIVE_OBJECTS = [
  {
    id: "star-1",
    component: "star-1",
    position: [450, 200, -300],
    size: 35,
  },
  {
    id: "star-2",
    component: "star-2",
    position: [-450, 220, 150],
    size: 28,
  },
  {
    id: "star-3",
    component: "star-3",
    position: [-100, -700, -200],
    size: 42,
  },
  {
    id: "star-4",
    component: "star-4",
    position: [-500, -150, 350],
    size: 31,
  },
  {
    id: "star-5",
    component: "star-5",
    position: [150, 450, 250],
    size: 38,
  },
  {
    id: "star-6",
    component: "star-6",
    position: [-250, -350, -400],
    size: 33,
  },
];

// Configuration par défaut pour les objets
export const DEFAULT_OBJECT_CONFIG = {
  size: 100,
  useVibration: false,
  vibrationIntensity: 1,
  vibrationSpeed: 1,
  isInteractive: false,
  boundingBox: {
    width: 100,
    height: 100,
    depth: 100,
  },
};
